apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deploy.name}}
  namespace: {{.Values.deploy.namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Values.deploy.name}}
  replicas: 1
  template:
    metadata:
      annotations: 
        buildNumber: {{.Values.deploy.build | quote}}
      labels:
        app: {{.Values.deploy.name}}
    spec:
      containers:
      - name: {{.Values.deploy.name}}
        image:  "{{.Values.deploy.acrServer}}/{{.Values.deploy.name}}:{{.Values.deploy.imageTag}}"
        ports:
          - name: http
            containerPort: 8080   
        imagePullPolicy: Always    
      imagePullSecrets:
        - name: {{.Values.deploy.secretName}}