name: Build Java Gradle

on:
  workflow_call:
    secrets:
      RETO_GITHUB_TOKEN:
        required: true
      RETO_SONAR_TOKEN:
        required: true

jobs:
  build_java_gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build, Test and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.RETO_SONAR_TOKEN }}
      run: ./gradlew build test sonar --info
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs