name: Create And Publish Docker Image

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ghcr:
    runs-on: ubuntu-latest
    permissions: write-all
      # contents: read
      # packages: write
      # id-token: write
      # attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: package
          path: build/libs

      - name: Display structure of downloaded files
        run: ls -R build/libs

      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  acr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: azure/docker-login@v2
      with:
        login-server: acrreto.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t acrreto.azurecr.io/calculator-java-gradle:${{ github.sha }}
        docker push acrreto.azurecr.io/calculator-java-gradle:${{ github.sha }}