name: DAST

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
      RESOURCE_GROUP:
        required: true
      CLUSTER_NAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
jobs:
  dast:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      NAMESPACE: qa-reto
      ACR_SERVER: acrreto.azurecr.io
      IMAGE_NAME: calculator-java-gradle
      SECRET_NAME: attach-acr-to-aks
      IMAGE_TAG: ${{ github.run_number }}
      BUILD_ID: ${{ github.run_id }}
      ACR_NAME: acrreto
      ACR_PASS: ${{ secrets.REGISTRY_PASSWORD }}
      SMOKE_TEST_CONTEXT: build-id
      IP_ADDRESS: localhost

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        id: login
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v4
        with:
          resource-group: '${{ secrets.RESOURCE_GROUP }}' 
          cluster-name: '${{ secrets.CLUSTER_NAME }}'

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v4

      - name: External IP
        run: |
          IP_ADDRESS=$(kubectl get svc calculator-java-gradle -n qa-reto -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://${{ env.IP_ADDRESS }}:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Publish Attestation DAST
        uses: actions/upload-artifact@v4
        with:
          name: dast-reports
          path: ./report_html.html