name: Reto DevSecOps

on:
  workflow_dispatch:

jobs:
  developmentIntegration:
    uses: retodevsecops/calculator-java-gradle/.github/workflows/buildJavaGradle.yml@main
    secrets:
      RETO_GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}
      RETO_SONAR_TOKEN: ${{ secrets.RETO_SONAR_TOKEN }}
  
  # technicalExcellenceAssurance:
  #   uses: retodevsecops/calculator-java-gradle/.github/workflows/sastAndSca.yml@main
  #   secrets:
  #     RETO_GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}

  artifactsManagement:
    # needs: [developmentIntegration, technicalExcellenceAssurance]
    needs: [developmentIntegration]
    uses: retodevsecops/calculator-java-gradle/.github/workflows/createAndPublishDockerImage.yml@main
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  
  ecosystemIntegration:
    # needs: [developmentIntegration, technicalExcellenceAssurance]
    needs: [artifactsManagement]
    uses: retodevsecops/calculator-java-gradle/.github/workflows/releaseKubernetes.yml@main
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}