name: Build Java Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_java_gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.RETO_SONAR_TOKEN }}
        
    - name: Build with Gradle Wrapper
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Artifact-${{ github.repository_id }}
        path: build/libs/
