name: Reto DevSecOps

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  developmentIntegration:
    uses: retodevsecops/calculator-java-gradle/.github/workflows/buildJavaGradle.yml@main
    secrets:
      RETO_GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}
      RETO_SONAR_TOKEN: ${{ secrets.RETO_SONAR_TOKEN }}
  
  technicalExcellenceAssurance:
    uses: retodevsecops/calculator-java-gradle/.github/workflows/sastAndSca.yml@main
    if: github.event.ref == 'refs/heads/main'
    secrets:
      RETO_GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}

  artifactsManagement:
    needs: [developmentIntegration,technicalExcellenceAssurance]
    uses: retodevsecops/calculator-java-gradle/.github/workflows/createAndPublishDockerImage.yml@main
    if: github.event.ref == 'refs/heads/main'
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  
  ecosystemIntegration:
    needs: [artifactsManagement]
    uses: retodevsecops/calculator-java-gradle/.github/workflows/releaseKubernetes.yml@main
    if: github.event.ref == 'refs/heads/main'
    with:
      NAMESPACE: 'qa-reto'
      ENVIRONMENT: 'qa'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    
  securityTesting:
    needs: [ecosystemIntegration]
    uses: retodevsecops/calculator-java-gradle/.github/workflows/dast.yml@main
    if: github.event.ref == 'refs/heads/main'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  
  deliveryProduction:
    needs: [securityTesting]
    uses: retodevsecops/calculator-java-gradle/.github/workflows/releaseKubernetes.yml@main
    if: github.event.ref == 'refs/heads/main'
    with:
      NAMESPACE: 'pdn-reto'
      ENVIRONMENT: 'production'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  
  semanticRelease:
    needs: [deliveryProduction]
    uses: retodevsecops/calculator-java-gradle/.github/workflows/publishVersion.yml@main
    if: github.event.ref == 'refs/heads/main'
    secrets:
      RETO_GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}
      RETO_SONAR_TOKEN: ${{ secrets.RETO_SONAR_TOKEN }}