name: Reto DevSecOps

on:
  workflow_dispatch:

jobs:
  developmentIntegration:
    uses: retodevsecops/calculator-java-gradle/.github/workflows/buildJavaGradle.yml@main
    secrets:
      RETO_GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}
      RETO_SONAR_TOKEN: ${{ secrets.RETO_SONAR_TOKEN }}
  
  technicalExcellenceAssurance:
    uses: retodevsecops/calculator-java-gradle/.github/workflows/sast.yml@main
    secrets:
      RETO_GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}
  
  artifactsManagement:
    needs: [developmentIntegration, technicalExcellenceAssurance]
    uses: retodevsecops/calculator-java-gradle/.github/workflows/buildAndPublishDockerImage.yml@main
    with:
      image_name: calculator_java_gradle
      tag: $GITHUB_RUN_NUMBER