name: SAST and SCA

on:
  workflow_call:
    secrets:
      RETO_GITHUB_TOKEN:
        required: true

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run ShiftLeft SAST Scan
      run: |
        docker run --rm -v ${{ github.workspace }}:/app:cached -v ${{ github.workspace }}/reports:/reports:cached shiftleft/sast-scan scan --src /app --out_dir /reports/static-analysis
        report_files=$(find ${{ github.workspace }}/reports/static-analysis -name "*.json")
        echo "Found report files: $report_files"
    
    - name: Upload ShiftLeft Reports
      uses: actions/upload-artifact@v4
      with:
        name: sast-reports
        path: reports/static-analysis/*.json

  sca:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'test'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired
          
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
          name: sca-reports
          path: ${{github.workspace}}/reports