name: SAST

on:
  workflow_call:
    secrets:
      RETO_GITHUB_TOKEN:
        required: true

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run ShiftLeft SAST Scan
      run: |
        docker run --rm -v ${{ github.workspace }}:/app:cached -v ${{ github.workspace }}/reports:/reports:cached shiftleft/sast-scan scan --src /app --out_dir /reports/static-analysis
        report_files=$(find ${{ github.workspace }}/reports/static-analysis -name "*.json")
        echo "Found report files: $report_files"
    
    - name: Upload ShiftLeft Reports
      uses: actions/upload-artifact@v3
      with:
        name: shiftleft-reports
        path: reports/static-analysis/*.json
    
    # - name: Perform Scan
    #   uses: ShiftLeftSecurity/scan-action@master
    #   with:
    #     type: "credscan,java,depscan"
    #   env:
    #     WORKSPACE: https://github.com/${{ github.repository }}
    #     GITHUB_TOKEN: ${{ secrets.RETO_GITHUB_TOKEN }}

    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: reports
    #     path: reports